import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("./pages/HomePage.tsx"),
  route("products", "./pages/ProductsPage.tsx"),
  route("categories", "./routes/categories-redirect.tsx"),
  route("products/category/:slug", "./routes/category-shop.tsx"),
  route("products/:slug", "./pages/ProductDetailPage.tsx"),
  route("blog", "./pages/BlogListPage.tsx"),
  route("blog/:slug", "./pages/BlogDetailPage.tsx"),
  route("city/:slug", "./pages/CityPage.tsx"),
  route("gift", "./pages/GiftPage.tsx"),
  route("corporate", "./pages/CorporatePage.tsx"),
  route("reviews", "./pages/ReviewsPage.tsx"),
  route("quality", "./pages/QualityPage.tsx"),
  route("about", "./pages/AboutPage.tsx"),
  route("gallery", "./pages/GalleryPage.tsx"),
  route("faq", "./pages/FAQPage.tsx"),
  route("contact", "./pages/ContactPage.tsx"),
  route("privacy", "./pages/PrivacyPage.tsx"),
  route("terms", "./pages/TermsPage.tsx"),
  route("shipping", "./pages/ShippingPage.tsx"),
  route("cart", "./routes/cart.tsx"),
  route("checkout", "./routes/checkout.tsx"),
  route("payment/mock", "./routes/payment-mock.tsx"),
  route("payment/callback", "./routes/payment-callback.tsx"),
  route("account/login", "./routes/account-login.tsx"),
  route("account", "./routes/account.tsx"),
  route("account/orders/:orderId", "./routes/account-order.tsx"),
  route("*", "./routes/not-found.tsx"),
] satisfies RouteConfig;
